### ISSUE TITLE
Ordem alfabética

### ISSUE THREAD

**Issue by walmyrcarvalho** [joselitojunior/slack-list-brazil#34]
Faz sentido deixar em ordem alfabética? Me incomodou um pouco não estar. hahaha

No mais, ótima iniciativa. :)

**Comment by joselitojunior** [comment]
Não tinha ordem exata pois não tinha um bom numero que exigisse tal. Acho interessante a ordem alfabética. Podes alterar e mandar um pr @walmyrcarvalho?

**Comment by walmyrcarvalho** [comment]
@joselitojunior Subi um PR, fiz meio correndo hahah se tiver qualquer problema me avisa. https://github.com/joselitojunior/slack-list-brazil/pull/35

Novamente, ótima idéia, parabéns pela iniciativa. :)
